# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yidao620c.github.io
title: 笨跑的一刀
subtitle: Code is sexy, like Amy!
author: 熊能
simple_search: https://www.google.com.hk/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%Y年%m月%d日"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email: yidao620@gmail.com
# RSS feeds can list your email address if you like
email: yidao620@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year:month:day/:title.html
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
category_title_prefix: "分类目录："
markdown: kramdown
#markdown: rdiscount
#rdiscount:
#  extensions:
#    - autolink
#    - footnotes
#    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "「阅读全文」&rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: yidao620c
github_repo_count: 0
github_show_profile_link: false
github_skip_forks: true

# Twitter
twitter_user: yidao620@gmail.com
twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: yidao620@gmail.com
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: yidao620cgithubio
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false


# 博客同步插件
#MetaWeblog:
#   Cnblogs:
#      MetaWeblog_username: yidao620c
#      MetaWeblog_url: http://www.cnblogs.com/yidao620c/services/metaweblog.aspx
#      MetaWeblog_blogid: 145005
#   SINA:
#       MetaWeblog_username: yidao620@163.com
#       MetaWeblog_url: http://upload.move.blog.sina.com.cn/blog_rebuild/blog/xmlrpc.php
#       MetaWeblog_blogid: 200000
#   51CTO:
#       MetaWeblog_username: yidao620@163.com
#       MetaWeblog_url: http://yidao620c.blog.51cto.com/xmlrpc.php
#       MetaWeblog_blogid: 200003
#   OSchina:
#       MetaWeblog_username: yidao620@163.com
#       MetaWeblog_url: http://my.oschina.net/yidao620c/blog
#       MetaWeblog_blogid: 200002
#    163blog:
#       MetaWeblog_username: yidao620@163.com
#       MetaWeblog_url: http://yidao620.blog.163.com/
#       MetaWeblog_blogid: 200001